baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Qui sommes nous?'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Nos activités'
    pageRef = '/actu'
    weight = 20

  [[menus.main]]
    name = 'Nos membres'
    pageRef = '/membres'
    weight = 30

  [[menus.main]]
    name = 'Autour de nous'
    pageRef = '/autour'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
