baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Qui sommes nous?'
    pageRef = '/membres'
    weight = 10

  [[menus.main]]
    name = 'Nos activités'
    pageRef = '/actu'
    weight = 20

  [[menus.main]]
    name = 'Nous contacter'
    pageRef = '/contacts'
    weight = 30

  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 40
    
  [[menus.main]]
    name = 'Nos partenaires'
    pageRef = '/partenaires'
    weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
